FROM node:7.8.0

WORKDIR /var/www/

RUN npm install -g gulp jspm

# Install app dependencies
COPY ./package.json /var/www

RUN npm install

RUN jspm install

COPY . /var/www

RUN npm run export

CMD ["/bin/bash"]
